---
  copyright_image: "http://licensebuttons.net/l/by/4.0/80x15.png"
  copyright_image_link: "http://creativecommons.org/licenses/by/4.0/"
  copyright_text: "Except where otherwise noted, content on this site is licensed under a Creative Commons Attribution License. (CC-BY)"
