---
  header_logo_url: /image/epsilosimple_logo.png
  header_logo_text: UCFC Database
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
    
    - label: Recent Addition
      link: /newspecimens
